<?php $data = $this->viewData ?>

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="refresh" content="3600">
	<meta name="viewport" content="width=device-width"/>
	<link rel="stylesheet"  type="text/css" href="resource/css/style.css"/>
	<link rel="stylesheet" media="only screen and (max-width: 800px)" type="text/css" href="resource/css/mobile.css"/>
	<link rel=icon href=resource/images/favicon.png type="image/png">
	<!--<link rel="stylesheet" media="screen and (device-aspect-ratio: 40/71) " type="text/css" href="resource/css/mobile.css"/>-->

	<script type="text/javascript" src="../../lib/jquery/jquery-2.1.1.min.js"></script>
	<title>Top 10 Weather Data</title>
</head>
<body>
<div class="content">
	<div class="left">
			<?= "API Speed: " . number_format($data['time'], 3) . 's'; ?>
			<h1><?= $data['h1'] ?></h1>


			<?php $selfUrl = $_SERVER['PHP_SELF'];

			include('selectTable.phtml');

			if ($data['selectedUnit'] == 'metric') {
				$formatTemp = 'C';
				$formatWind = 'm/s';
			} else {
				$formatTemp = 'F';
				$formatWind = 'mph';
			}
			?>
			<div class="empty"></div>
			<table class="weatherInfo">
				<tr>
<!--					<td>--><?//= $language['city'] ?><!--</td>-->
					<td colspan="2" id="city_title"><?= $data['result']->name . ', ' . $data['result']->sys->country ?></td>
				</tr>
				<?php $coords = $data['result']->coord->lat . '&deg, ' . $data['result']->coord->lon . '&deg';
				$linker = "http://maps.google.com/?q=" . $coords; ?>
				<tr>
					<td><?= $language['lat'] ?></td>
					<td><a target="_blank" href="<?= $linker ?>"><?= $coords ?></a></td>
				</tr>
				<tr>
					<td colspan="2"><img src="<?= $data['icon'] ?>" alt="Weather Icon"><br><?= ucwords($data['result']->weather[0]->description) ?></td>
				</tr>

				<tr>
					<td class="none"></td>
				</tr>
				<tr>
					<td colspan="2"><?= date('d/m/y @ H:m') ?></td>
				</tr>
				<tr>
					<td><?= $language['sunrise'] ?></td>
					<td><?= date('H:m', $data['result']->sys->sunrise) ?></td>
				</tr>
				<tr>
					<td><?= $language['sunset'] ?></td>
					<td><?= date('H:m', $data['result']->sys->sunset) ?></td>
				</tr>
				<tr>
					<td class="none"></td>
				</tr>
				<tr>
					<td><?= $language['temp'] ?></td>
					<td><?= number_format($data['result']->main->temp, 2) ?>&deg<?= $formatTemp ?></td>
				</tr>
				<tr>
					<td><?= $language['mintemp'] ?></td>
					<td><?= number_format($data['result']->main->temp_min, 2) ?>&deg<?= $formatTemp ?></td>
				</tr>
				<tr>
					<td><?= $language['maxtemp'] ?></td>
					<td><?= number_format($data['result']->main->temp_max, 2) ?>&deg<?= $formatTemp ?></td>
				</tr>
				<tr>
					<td class="none"></td>
				</tr>

				<tr>
					<td><?= $language['humidity'] ?></td>
					<td><?= $data['result']->main->humidity ?>%</td>
				</tr>
				<tr>
					<td><?= $language['wind'] ?></td>
					<td><?= number_format($data['result']->wind->speed, 1) . ' ' . $formatWind ?></td>
				</tr>
			</table>
			<div class="empty"></div>

			<table class="config">
				<tr>
					<td>
						<a href="#info"><img src="../../resource/images/info.png" onclick="$('#info').toggle()"/></a>

						<div id="info" style="display:none">
							Additional you can enter this after the url<br><br>
							A city has to be a valid city [cityname,country codes]<br>
							Units have to be enter as followed [metric] or [imperial]<br><br>

							For example:<br>
							<a href="?city=paris,fr&unit=metric">?city=paris,fr&unit=metric</a><br>
							<a href="?city=berlin,de&units=imperial">?city=berlin,de&units=imperial</a>
						</div>
					</td>
				</tr>
			</table>
		<br>
	</div>

	<div class="right">
		<iframe class="iframe" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
		src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=<?= $data['result']->name ?>
		&amp;ie=UTF8&amp;t=m&amp;z=11&amp;ll=<?= $data['result']->coord->lat . ',' . $data['result']->coord->lon ?>&amp;output=embed"></iframe>
	</div>
</div>

</body>
</html>
